@devUrl=http://localhost:3001
###GET
//usuarios insertar id
GET {{devUrl}}/user/47
###clientes logueados
GET {{devUrl}}/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo0NywiaWF0IjoxNzA5MDQzMTYwLCJleHAiOjE3MDkwNDY3NjB9.VEqXyNFMBGrwr1PVBvdXYvSx7vVlP34G76PPXAUOgB8
###vendedor logueado
GET {{devUrl}}/seller
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo0OCwiaWF0IjoxNzA5ODYwODg5LCJleHAiOjE3MDk4NjQ0ODl9.0CeztRWrSTqd7He8eQgV4wRbllb8EDx7ocl031nGpjQ

###servicios del vendedor
GET {{devUrl}}/service
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo0OCwiaWF0IjoxNzA5ODYwODg5LCJleHAiOjE3MDk4NjQ0ODl9.0CeztRWrSTqd7He8eQgV4wRbllb8EDx7ocl031nGpjQ


###ruta privada de prueba para el login
GET {{devUrl}}/private
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo0NywiaWF0IjoxNzA4NzYyMjc5LCJleHAiOjE3MDg3NjU4Nzl9.IOfAXYQ7Qg5m95BiUcVJw9lU6jDXr_AJwTMGdoXFAOs

###
GET {{devUrl}}/sales
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo0OCwiaWF0IjoxNzA4OTk5ODQ2LCJleHAiOjE3MDkwMDM0NDZ9.HdoS5MMfKjrnFwkzduPly8X_sr37lTeZ-pANn1lnDuA
//rutas post
//usernames unicos no permite duplicados
###crear usuario con rol cliente
POST {{devUrl}}/user
Content-Type: application/json

{   
    "name":"sebastian",
    "lastname":"oliveto",
    "address":"ezeiza",
    "dni":"12345678",
    "birthdate":"1993-08-07",
    "country":"argentina",
    "phone":"12345678",
    "email":"sebas@hotmail.com",
    "role":"cliente",
    "user_state":true,
    "username":"sebas",
    "password":"sebas"
}
###crear usuario con rol empleado
POST {{devUrl}}/user
Content-Type: application/json

{   
    "name":"cristobal",
    "lastname":"colon",
    "address":"europa",
    "dni":"12348",
    "birthdate":"1993-08-07",
    "country":"argentina",
    "phone":"12345679",
    "email":"empleado1@hotmail.com",
    "role":"vendedor",
    "user_state":true,
    "username":"cristobal",
    "password":"cristobal",
    "job":"vendedor",
    "salary":1000
}

### creacion de servicio por parte de empleado
//el sistema verifica rol del usuario si es vendedor
POST {{devUrl}}/service
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo0OCwiaWF0IjoxNzA4NzYyNzA2LCJleHAiOjE3MDg3NjYzMDZ9.1kCocFk997pgbztXpG2SQrrHuftrZeImoIhA-_tvA1M

{
    "name":"hotel por noche",
    "description":"hotel con vista al mar 5 estrellas",
    "service_destination":"bolivia",
    "service_date":"2024-3-15",
    "cost":"470000",
    "service_code":1
}
//contraseña encriptada en ambos casos, acordarsela XD
### login cliente
POST {{devUrl}}/login
Content-Type: application/json

{
    "username":"sebas",
    "password":"sebas"
}
### login empleado
POST {{devUrl}}/login
Content-Type: application/json

{
    "username":"cristobal",
    "password":"cristobal"
}

###ventas
//para utilizar primero loguear un usuario cliente(proximamente solo clientes) y utilizar su toquen
//los servicios son los id identificadores de la tabla servicio
POST {{devUrl}}/sales
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo0NywiaWF0IjoxNzA4OTkyNDkyLCJleHAiOjE3MDg5OTYwOTJ9.GGCCeDN50zpeW02T-OP7HtKtRhr9gmjL1hoj9WKuY44

{
    "id_servicios":[4],
    "payment_method":"mercado-pago"
}

### rutas PATCH
//modificamos cliente se puede enviar menos datos
PATCH {{devUrl}}/client
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo0NywiaWF0IjoxNzA5MDQ3NDc3LCJleHAiOjE3MDkwNTEwNzd9.9mcrxvRk8HnynbW_8jyZzPntxMwcxRn6epOfvoKQkEM

{  
      "name": "sebastian",
      "email": "modificado@hotmail.com",        
      "phone": "1122334455",
      "address": "ezeiza",  
      "country": "argentina",
      "lastname": "oliveto"       
}
### modificamos empleado se puede enviar menos datos
PATCH  {{devUrl}}/seller
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo0OCwiaWF0IjoxNzA5MDQ3OTM3LCJleHAiOjE3MDkwNTE1Mzd9.UThUf1hKPGobx1exgjCEknqhlucMDbR2eOb0SweLGyw

{   
    "country":"argentina"
}

### rutas delete se elimina por id cliente/empleado y automaticamente se elimina el usuario asociado
//actualizacion se cambio por baja logica el usuario se agrego baja=false/true
//ya no se utiliza la baja fisica en la bd.Se conservan los datos
//user
DELETE {{devUrl}}/user/42
### 
DELETE {{devUrl}}/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo0NywiaWF0IjoxNzA5MDQ3NDc3LCJleHAiOjE3MDkwNTEwNzd9.9mcrxvRk8HnynbW_8jyZzPntxMwcxRn6epOfvoKQkEM

###
//vendedor
DELETE {{devUrl}}/seller
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo0OCwiaWF0IjoxNzA5MDQ3OTM3LCJleHAiOjE3MDkwNTE1Mzd9.UThUf1hKPGobx1exgjCEknqhlucMDbR2eOb0SweLGyw