@devUrl=http://localhost:3001
###GET
//usuarios insertar id
GET {{devUrl}}/user/1
###clientes insertar id
GET {{devUrl}}/client/1

###vendedor 
GET {{devUrl}}/seller/1

###ruta privada de prueba para el login
GET {{devUrl}}/private
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkX3VzdWFyaW8iOjQzLCJub21icmUiOiJudWV2byIsImFwZWxsaWRvIjoibnVldm8iLCJkaXJlY2Npb24iOiJudWV2byIsImRuaSI6MTIzNDU2LCJmZWNoYV9uYWMiOiIxOTkzLTA4LTA3VDAzOjAwOjAwLjAwMFoiLCJuYWNpb25hbGlkYWQiOiJhcmdlbnRpbmEiLCJjZWx1bGFyIjoxMjM0NTY3OCwiZW1haWwiOiJudWV2b0Bob3RtYWlsLmNvbSIsInJvbCI6ImNsaWVudGUiLCJ1c2VybmFtZSI6InNlYmkzIiwicGFzc3dvcmQiOiIkMmEkMTAkdzRGeTNwZTNhcHg5SjFqNnRoWkFndUlSc2FjRTZrRzJnS3IvdXVEZXRoQzA3M1BuL2dPV3kifSwiaWF0IjoxNzA4MzU3OTM2LCJleHAiOjE3MDgzNjE1MzZ9.gzXk1SL7GAmgv1EVzghYruhQztZR5LhTn1_ZDA_1StA


//rutas post
//usernames unicos no permite duplicados
###crear usuario con rol cliente
POST {{devUrl}}/user
Content-Type: application/json

{   
    "name":"sebastian",
    "lastname":"oliveto",
    "address":"ezeiza",
    "dni":"12345678",
    "birthdate":"1993-08-07",
    "country":"argentina",
    "phone":"12345678",
    "email":"sebas@hotmail.com",
    "role":"cliente",
    "user_state":true,
    "username":"sebas",
    "password":"sebas"
}
###crear usuario con rol empleado
POST {{devUrl}}/user
Content-Type: application/json

{   
    "name":"cristobal",
    "lastname":"colon",
    "address":"europa",
    "dni":"12348",
    "birthdate":"1993-08-07",
    "country":"argentina",
    "phone":"12345679",
    "email":"empleado1@hotmail.com",
    "role":"vendedor",
    "user_state":true,
    "username":"cristobal",
    "password":"cristobal",
    "job":"vendedor",
    "salary":1000
}

### creacion de servicio por parte de empleado
//el sistema verifica rol del usuario si es empleado
POST {{devUrl}}/service
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkX3VzdWFyaW8iOjQ2LCJjcmVhdGVkX2F0IjoiMjAyNC0wMi0yNFQwMjowMzo0Ny42MTAzMTIrMDA6MDAiLCJuYW1lIjoiY3Jpc3RvYmFsIiwibGFzdG5hbWUiOiJjb2xvbiIsImFkZHJlc3MiOiJldXJvcGEiLCJkbmkiOjEyMzQ4LCJiaXJ0aGRhdGUiOiIxOTkzLTA4LTA3IiwiY291bnRyeSI6ImFyZ2VudGluYSIsInBob25lIjoiMTIzNDU2NzkiLCJyb2xlIjoidmVuZGVkb3IiLCJ1c2VyX3N0YXRlIjp0cnVlLCJ1c2VybmFtZSI6ImNyaXN0b2JhbCIsInBhc3N3b3JkIjoiJDJhJDEwJGlvLzNZVlhyOE9ERm92YXAuOENUQ09xNjhpR1BLNEM4SXFnNEZrQm5xaW5HRXhRZzBVaVlHIiwiZW1haWwiOiJlbXBsZWFkbzFAaG90bWFpbC5jb20ifSwiaWF0IjoxNzA4NzQwMjM0LCJleHAiOjE3MDg3NDM4MzR9.hSWZa1fozzsKha2FOGdq7E9dGErmP7mCb9Q4MJVa77o

{
    "name":"entrada a eventos",
    "description":"cosquin rock",
    "service_destination":"cordoba",
    "service_date":"2024-2-15",
    "cost":"30000",
    "service_code":7
}
//contraseña encriptada en ambos casos, acordarsela XD
### login cliente
POST {{devUrl}}/login
Content-Type: application/json

{
    "username":"prueba17",
    "password":"prueba17"
}
### login empleado
POST {{devUrl}}/login
Content-Type: application/json

{
    "username":"cristobal",
    "password":"cristobal"
}

###ventas
//para utilizar primero loguear un usuario cliente(proximamente solo clientes) y utilizar su toquen
//los servicios son los id identificadores de la tabla servicio
POST {{devUrl}}/sales
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkX3VzdWFyaW8iOjMwLCJjcmVhdGVkX2F0IjoiMjAyNC0wMi0yM1QwMjoxMjoyMC4xMzEyMjcrMDA6MDAiLCJuYW1lIjoic2ViYXN0aWFuIiwibGFzdG5hbWUiOiJvbGl2ZXRvIiwiYWRkcmVzcyI6ImV6ZWl6YSIsImRuaSI6MTI1MjE2MjI0LCJiaXJ0aGRhdGUiOiIxOTkzLTA4LTA3IiwiY291bnRyeSI6ImFyZ2VudGluYSIsInBob25lIjoiMTEyMjMzNDQ1NSIsInJvbGUiOiJjbGllbnRlIiwidXNlcl9zdGF0ZSI6dHJ1ZSwidXNlcm5hbWUiOiJwcnVlYmExNyIsInBhc3N3b3JkIjoiJDJhJDEwJDAydWtvRHBlYnMxQk92WGpDNkQ5ZXVxWmJHYy8vTWk3LlVwTW9OUXZES3oxLzFmdTl4ZmFLIiwiZW1haWwiOiJzZWJhc0Bob3RtYWlsLmNvbSJ9LCJpYXQiOjE3MDg3MzczMTAsImV4cCI6MTcwODc0MDkxMH0.I8gU07Rvjj2FYp5uz2R1t2F2UEOgOzGXSF66aid7lyQ

{
    "id_servicios":[1,2],
    "payment_method":"mercado-pago"
}

### rutas PATCH
//modificamos cliente se puede enviar menos datos
PATCH {{devUrl}}/client/4
Content-Type: application/json

{  
      "name": "sebastian",
      "email": "sebas@hotmail.com",        
      "phone": "1122334455",
      "address": "ezeiza",  
      "country": "argentina",
      "lastname": "oliveto"       
}
### modificamos empleado se puede enviar menos datos
PATCH  {{devUrl}}/seller/2
Content-Type: application/json

{   
    "name":"sebas",
    "lastname":"oliveto",
    "address":"ezeiza",
    "dni":"183456",
    "birthdate":"1993-08-07",
    "country":"argentina",
    "phone":"12345678",
    "email":"nuevo@hotmail.com",
    "job":"gerente",
    "salary":"15000"
}

### rutas delete se elimina por id cliente/empleado y automaticamente se elimina el usuario asociado
//actualizacion se cambio por baja logica el usuario se agrego baja=false/true
//ya no se utiliza la baja fisica en la bd.Se conservan los datos
//user
DELETE {{devUrl}}/user/42
### 
DELETE {{devUrl}}/client/1

###
//vendedor
DELETE {{devUrl}}/seller/1
